[tool.poetry]
name = "embedchain"
version = "0.0.10"
description = "embedchain is a framework to easily create LLM powered bots over any dataset"
authors = ["Taranjeet Singh"]
license = "Apache License"
readme = "README.md"
packages = [{include = "embedchain"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
python-dotenv = "^1.0.0"
langchain = "^0.0.205"
requests = "^2.31.0"
openai = "^0.27.5"
chromadb ="^0.3.26"
youtube-transcript-api = "^0.6.1"
beautifulsoup4 = "^4.12.2"
pypdf = "^3.11.0"
pytube = "^15.0.0"
pre-commit = "^3.3.3"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pre-commit = "^3.2.2"
ruff = "^0.0.220"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"
pytest-env = "^0.8.1"
click = "^8.1.3"

[tool.poetry.extras]
streamlit = ["streamlit"]



[tool.poetry.group.docs.dependencies]


[tool.poetry.scripts]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = ["tests_*"]

[tool.pytest.ini_options]
env = [
    "HUGGINGFACE_API_KEY=",
    "OPENAI_API_KEY="
]
