app:
  config:
    id: azure-openai-app

llm:
  provider: azure_openai
  model: gpt-35-turbo
  config:
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false

embedder:
  provider: azure_openai
  config:
    model: text-embedding-ada-002
    deployment_name: my_azure_deployment_name
